<?php
namespace Helmich\Graphizer\Console\Command;


use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ExportCodeCommand extends AbstractCommand {

	protected function configure() {
		$this
			->setName('export:php')
			->setDescription('Export back into PHP source files')
			->addArgument('target', InputArgument::REQUIRED, 'Target directory');
	}

	protected function execute(InputInterface $input, OutputInterface $output) {
		parent::execute($input, $output); // TODO: Change the autogenerated stub
	}
}